FROM 32bit/ubuntu:14.04
MAINTAINER Matthieu Velay mvelay@gmail.com

VOLUME /home/mvelay
VOLUME /home/mvelay/test

RUN mkdir /root/.ssh/


ADD id_rsa /root/.ssh/id_rsa


CMD /bin/sh -c "echo 'test_container'"

